### PR TITLE
convert to typescript

### PR DESCRIPTION
**Pull request by toddself**

### CODE REVIEW

**Comment by toddself** [comment]
typescript version:

```[20:52:23] $ npm publish --dry-run
npm notice
npm notice 📦  nanorequest@2.0.3
npm notice === Tarball Contents ===
npm notice 939B  package.json
npm notice 554B  LICENSE
npm notice 3.2kB README.md
npm notice 589B  dist/nanorequest.d.ts
npm notice 3.5kB dist/nanorequest.js
npm notice === Tarball Details ===
npm notice name:          nanorequest
npm notice version:       2.0.3
npm notice package size:  3.4 kB
npm notice unpacked size: 8.7 kB```

**Comment by toddself** [comment]
Removes all dependencies yayyayayayayayay

**Comment by toddself** [comment]
@ungoldman this should be a non-breaking minor change, but like, ¯\_(ツ)_/¯.

(the tests pass without change which leads me to believe it's okay-doaky, but given the heavy reliance on this library i don't want to mess y'all up)

**Comment by toddself** [comment]
(also there is no rush!)

**Review by ungoldman — APPROVED** [review]
as long as the exported interface is the same 👍

**Comment by toddself** [comment]
:package: 3.0.0

**Comment by ungoldman** [comment]
breaking change?

**Comment by toddself** [comment]
yeah, i figure it's a new programming language it's been written in.  while the original test suite still passes, there might be subtle enough behavior introduced with the compiler that i didn't want to risk it.

**Pull request merged**
